---
title: "Processing & Visualizing Flowthrough"
author: "Laura E. Wiltsee"
date: "6/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("M3")
library("dplyr")
library("gam")
library ("readxl")
library("car")
library("GGally")
library('gamlss')
library("psych")
library("imputeTS")
library("forecast")
library("Metrics")
library("tidyverse")
library("reticulate")

rm()
```

Analysis of second-by-second Chlorophyll a measurements to determine individual oyster feeding rate variation on a daily timescales

```{r}
##### Things to change #######
date= "220602"
date_long= "June 02, 2022"

# Can find a way to automate this with "size_traits_LEW.xlsx"
o1_dt= 3.52
o2_dt= 3.79
o3_dt= 3.95
bw= 2.22 # Boat Weight in grams (enter zero if dw does not include weigh boat)
```

Function to prepare the fluorometery data.
```{r prep_fluoro}
prep_fluoro= function(chamber) {
  dat= read.csv(paste0(date,chamber))
  dat$datetime= as.POSIXct(paste(dat$Date, dat$Time), format="%m/%d/%Y %H:%M:%S")
  dat.new= subset(dat, select= c("datetime","mV")) # Selects just the mV and time
  if (all(dat['Gain']=="10x")) {
    return(dat.new)
  } else {print ("Not all gains are the same!")}
}

control= prep_fluoro("_com5.csv")
o1= prep_fluoro("_com8.csv")
o2= prep_fluoro("_com7.csv")
o3= prep_fluoro("_com6.csv")
```

```{r, warning=FALSE}
dat1= merge(x= control, y= o1, by= "datetime", all= TRUE)
dat2= merge(x= dat1, y= o2, by= "datetime", all= TRUE)
dat3= merge(x= dat2, y= o3, by= "datetime", all= TRUE)
dat= na.omit(dat3)
colnames(dat)= c("dattime","control","o1","o2","o3")
```

Plotting Raw mV values
```{r}
plot(x= dat$dattime, y= dat$control, col=1, type="l")
plot(x= dat$dattime, y= dat$o1, col=2, type="l")
plot(x= dat$dattime, y= dat$o2, col=3, type="l")
plot(x= dat$dattime, y= dat$o3, col=4, type="l")
```


```{r}
####### Calibration #########
cal= function(chamber,blank,std) {
  pre= 10/(std-blank)
  cal_new = (chamber - blank)* pre
  return(cal_new)
}

dat$Control_cal= cal(dat$control,17,77)
dat$o1_cal= cal(dat$o1,17,86)
dat$o2_cal= cal(dat$o2,15,79)
dat$o3_cal= cal(dat$o3,17,79)

#### Converting to CR in mg/L #####
cr= function(chamber, control, fr) {
  o_cr= fr*((control-chamber)/control)
  return(o_cr)
}

dat$o1_cr= cr(dat$o1_cal, dat$Control_cal, 7)
dat$o2_cr= cr(dat$o2_cal, dat$Control_cal, 7)
dat$o3_cr= cr(dat$o3_cal, dat$Control_cal, 7)
```

Correcting for Dry Weight
```{r}
dat$o1_crdw= dat$o1_cr/(o1_dt-bw)
dat$o2_crdw= dat$o2_cr/(o2_dt-bw)
dat$o3_crdw= dat$o3_cr/(o3_dt-bw)
```

Plotting Raw L/g/hr Values
```{r}
plot(x= dat$dattime, y= dat$o1_crdw, col=2, type="l")
plot(x= dat$dattime, y= dat$o2_crdw, col=3, type="l")
plot(x= dat$dattime, y= dat$o3_crdw, col=4, type="l")
```

```{r, echo=FALSE, results='hide'}
jpeg(file=paste(date,"_CR_plot.jpeg")) # Creates a jpeg of the plot that is updated every time
dat_clean= dat[c(1:70000),]
plot(x= dat_clean$dattime, y= dat_clean$o1_crdw, col=2, type="l", ylab= "Oyster Clearance Rate (L/h/g DW)", xlab="Time", main=paste("Oyster Clearance Rate per Gram over Time for",date_long))
lines(x= dat_clean$dattime, y= dat_clean$o2_crdw, col= 3)
lines(x= dat_clean$dattime, y= dat_clean$o3_crdw, col= 4)
legend("bottomright", c("Oyster 1","Oyster 2", "Oyster 3"), col = 2:4,pch = 16)
dev.off()
```

Plotting Cleaned Data
```{r}
dat_clean= dat[c(1:70000),]
plot(x= dat_clean$dattime, y= dat_clean$o1_crdw, col=2, type="l", ylab= "Oyster Clearance Rate (L/h/g DW)", xlab="Time", main=paste("Oyster Clearance Rate per Gram over Time for",date_long))
lines(x= dat_clean$dattime, y= dat_clean$o2_crdw, col= 3)
lines(x= dat_clean$dattime, y= dat_clean$o3_crdw, col= 4)
legend("bottomright", c("Oyster 1","Oyster 2", "Oyster 3"), col = 2:4,pch = 16)
```


